name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install host dependencies
      run: |
        set -e
        python --version
        python -m pip install --upgrade pip
        python -m pip install --user --force \
            setuptools_scm \
            tox

    - uses: actions/checkout@v2

    - name: Pylint
      run: |
        python -m tox -e pylint -vv
    - name: Black
      run: |
        python -m tox -e blackcheck -vv

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install host dependencies
      run: |
        set -e
        python --version
        python -m pip install --upgrade pip
        python -m pip install --user --force \
            setuptools_scm \
            tox

    - uses: actions/checkout@v2

    - name: unit tests with coverage
      run: |
        python3 --version
        export CONSOLE_SCRIPTS_BASEPYTHON=/usr/bin/python3
        python3 -m tox -e py3-coverage -vv

  integration_tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    container:
      image: library/alt:sisyphus
      options: --privileged
    steps:
    - name: Install host dependencies
      run: |
        set -e
        apt-get update
        apt-get install -y \
            git \
            python3-modules-sqlite3 \
            python3-module-setuptools \
            python3-module-setuptools_scm \
            python3-module-tox
    - uses: actions/checkout@v2

    - name: unit and integration tests with coverage
      run: |
        python3 --version
        export CONSOLE_SCRIPTS_BASEPYTHON=/usr/bin/python3
        python3 -m tox -e py3-coverage -vv
